### ISSUE TITLE
skip when judging in a grouped subtasks pls

### ISSUE THREAD

**Issue by peteza6765** [karnjj/otog-grader#32]
**pls** do, very vu**lnerable to otog ติด t เกียนs**
![image](https://user-images.githubusercontent.com/86222502/232855114-98d25af0-b368-417c-ac57-892ecfea8f2f.png)

**Comment by Nepumi-Jr** [comment]
IDK mann
Can you clarify that in nowadays is it skip when judging in a grouped subtasks like `[PPPP-SSSS]` (when that test case is wrong answer, the other in that group testcase just skip) or it just keep judging like `[PPPP----P]` (that is I got used to).

Although It have a same score but the second one will tell more information to competitors. so What do you think about that @peteza6765 ?

**Comment by peteza6765** [comment]
i was talking about the first one where it just skips the other testcases in the group, i think the first one has enough information for the submitter, but idk bruh

**Comment by Nepumi-Jr** [comment]
What about CMS or IMSO grader. what are they handling this case?

**Comment by peteza6765** [comment]
IMSO doesnt skip, but im not sure about CMS, i think i have seen them skip before but i dont remember where
